### ISSUE TITLE
rundemo.py报错 FileNotFoundError

### ISSUE THREAD

**Issue by Li-rr** [zqbai-jeremy/DFNRMVS#2]
您好，我按readme.md 操作到run demo.py 

为啥会有这个错误

 FileNotFoundError: [Errno 2] No such file or directory: './external/face3d/examples/Data/BFM\\Out/BFM.mat'

**Comment by zqbai-jeremy** [comment]
可以试一下把DFNRMVS folder加入PYTHONPATH. `export PYTHONPATH=<DFNRMVS directory>`

**Comment by Li-rr** [comment]
您好,我试了以后还是不行,另外我检查了一下BGM.mat文件在报错信息提示的目录中没有找到,报错信息如下


~/workspace/DFNRMVS  master ✗                                                                                                                                39d13h ⚑ ◒  
▶ export PYTHONPATH=/home/lrr/workspace/DFNRMVS
(DFNRMVS) 
~/workspace/DFNRMVS  master ✗                                                                                                                                39d13h ⚑ ◒  
▶ python demo.py                               
Initializing model ...
Traceback (most recent call last):
  File "/home/lrr/anaconda3/envs/DFNRMVS/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 39, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: './external/face3d/examples/Data/BFM/Out/BFM.mat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 143, in <module>
    model = init_model(checkpoint_path)
  File "demo.py", line 47, in init_model
    model = FNRMVSNet(opt_step_size=1e-2)
  File "/home/lrr/workspace/DFNRMVS/networks/sub_nets.py", line 1083, in __init__
    self.opt_layer = NRMVSOptimization(opt_step_size=opt_step_size, MM_base_dir=MM_base_dir)
  File "/home/lrr/workspace/DFNRMVS/networks/sub_nets.py", line 553, in __init__
    self.bfm = bfm_utils.load_3DMM(MM_base_dir)
  File "/home/lrr/workspace/DFNRMVS/data/BFM/utils.py", line 69, in load_3DMM
    bfm = MorphabelModel(os.path.join(MM_base_dir, 'Out/BFM.mat'))
  File "/home/lrr/workspace/DFNRMVS/external/face3d/face3d/morphable_model/morphabel_model.py", line 30, in __init__
    self.model = load.load_BFM(model_path)
  File "/home/lrr/workspace/DFNRMVS/external/face3d/face3d/morphable_model/load.py", line 31, in load_BFM
    C = sio.loadmat(model_path)
  File "/home/lrr/anaconda3/envs/DFNRMVS/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 222, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "/home/lrr/anaconda3/envs/DFNRMVS/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/lrr/anaconda3/envs/DFNRMVS/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 17, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
  File "/home/lrr/anaconda3/envs/DFNRMVS/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 45, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: './external/face3d/examples/Data/BFM/Out/BFM.mat'
(DFNRMVS)

**Comment by zqbai-jeremy** [comment]
在目标路径上这个file存在吗？不存在的话需要setup YadiraF/face3d 里的 BFM (https://github.com/YadiraF/face3d/blob/master/examples/Data/BFM/readme.md).

**Comment by Li-rr** [comment]
可以了，谢谢您

还有一个问题就是，我现在用的windows的matlab生成BFM的out下面的东西，直接拷贝到ubuntu环境可以用吗

**Comment by Li-rr** [comment]
试好了，麻烦您了

**Comment by sunbin1993** [comment]
> 可以了，谢谢您
> 
> 还有一个问题就是，我现在用的windows的matlab生成BFM的out下面的东西，直接拷贝到ubuntu环境可以用吗

方便分享下 BFM.mat？？

**Comment by Li-rr** [comment]
> 
> 
> > 可以了，谢谢您
> > 还有一个问题就是，我现在用的windows的matlab生成BFM的out下面的东西，直接拷贝到ubuntu环境可以用吗
> 
> 方便分享下 BFM.mat？？

可以的，你的邮箱是多少

**Comment by enjoybo** [comment]
> > > 可以了，谢谢您
> > > 还有一个问题就是，我现在用的windows的matlab生成BFM的out下面的东西，直接拷贝到ubuntu环境可以用吗
> > 
> > 
> > 方便分享下 BFM.mat？？
> 
> 可以的，你的邮箱是多少

你好，我也想要一份BFM.mat, BFM_info.mat，电脑没装matlab没能生成，我的邮箱是626341449@qq.com，非常感谢~

**Comment by abhishekmaroon5** [comment]
I also want a copy of BFM.mat, BFM_info.mat. My email is [abhishekmaroon5@gmail.com](mailto:abhishekmaroon5@gmail.com)
